development:
  adapter: postgresql
  database: random_word_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: random_word_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: random_word_production
  pool: 5
  timeout: 5000
