# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a46ac1b66f16d26a76a45371fe4618f1f31ffd0b68f4c48a051fb73418691411b14f16ba63eca44940c532e5a78b60f96221b9fc1763fd3d378da7a9a67a92

test:
  secret_key_base: 4c18e8e87d3c8bb0d0f892f7f69a706acfb4a02a58ac4078d518fce607744dbe0535efd6254b72e387e201aebc2613538516a8d4224507190ad132a2622f614a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
